&fras "4.test"
⊜□⊸≠@\n
∵°□

Diag ← (
  ⊸(⇡⧻)
  ≡↻
  ⍉
)

DFind ← (
  ≡(⌕"XMAS")
  ≡⊢
  /+
)
⊃⇌∘
∩(⇡-3⊸⧻
  ⊙¤
  ⊞(□↘)
  /+≡(DFind Diag °□⊢)
)
+

# Find XMAS in all the directions
# Left to right, in all rows
# /+/+≡(⌕"XMAS").
# :
# # Right to left, in all rows
# /+/+≡(⌕"XMAS"⇌).
# ⊙+: # add to the total sum
# ⍉   # Columns are now rows and vice versa, so we can search vertically
# /+/+≡(⌕"XMAS").
# ⊙+: # add to the total sum
# /+/+≡(⌕"XMAS"⇌).
# ⊙+: # add to the total sum
